services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
      - storage:/var/www/html/storage
      - ../:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  storage:
  node_modules:
  vendor:
